name = input("wat is je naam")
adres = input("wat is je adres")
postcode = input("wat is je postcode")
woonplaats = input("wat is je woonplaats")

print("----------------------------------------")
print("|" + " " + "naam      :" + name)
print("|" + " " + "adres     :" + adres)
print("|" + " " + "postcode  :" + postcode)
print("|" + " " + "woonplaats:" + woonplaats)
print("----------------------------------------")